name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        type: [debug, release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: arm-none-eabi-gcc
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10.3-2021.10'

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Build binary
      run: |
        cmake --preset arm-cortex-m4-gcc-${{ matrix.type }}
        cmake --build --preset arm-cortex-m4-gcc-${{ matrix.type }}
